music/urls.py
from django.contrib import admin
from django.urls import path, include
from index import views
from django.conf.urls import url
from django.views import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('ranking/', include('ranking.urls')),
    path('play/', include('play.urls')),
    path('comment/', include('comment.urls')),
    path('search/', include('search.urls')),
    path('user/', include('user.urls')),
    # 设置项目上线的静态资源路径
    url('^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
]

# 设置404、500错误状态码
handler404 = views.page_not_found
handler500 = views.page_not_found

play/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.urls import path
from . import views

app_name = 'play'
urlpatterns = [
    # 歌曲播放页面
    path('<int:song_id>.html', views.play_view, name='play_view'),
    # 歌曲下载
    path('download/<int:song_id>.html', views.download_view, name='download'),
]

ranking/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.urls import path
from . import views

app_name = 'ranking'
urlpatterns = [
    path('', views.ranking_view, name='ranking_view'),
]

search/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('<int:page>.html', views.search_view, name='search_view'),
]

user/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    # 用户的注册和登录
    path('login.html', views.login_view, name='login_view'),
    # 用户中心
    path('home/<int:page>.html', views.home_view, name='home_view'),
    # 退出用户登录
    path('logout.html', views.logout_view, name='logout_view'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
# 自定义用户表：MyUser
class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=20)
    weChat = models.CharField('微信账号', max_length=30)
    mobile = models.CharField('手机号码', max_length=11, unique=True)

    # 设置放回值
    def __str__(self):
        return self.username

user/views.py
from django.shortcuts import render, redirect
from user.models import *
from django.db.models import Q
from django.contrib.auth import login, logout
from django.contrib.auth.hashers import check_password
from .form import MyUserCreationForm
from django.contrib.auth.decorators import login_required
from myutils import myutil
from index.models import *


# Create your views here.
# 用户注册和登录
def login_view(request):
    # 表单对象
    user = MyUserCreationForm()
    # 表单提交
    if request.method == 'POST':
        # 判断表单提交是用户登录还是注册
        # 用户登录
        if request.POST.get('loginUser', ''):
            loginUser = request.POST.get('loginUser', '')
            password = request.POST.get('password', '')
            if MyUser.objects.filter(Q(mobile=loginUser) | Q(username=loginUser)):
                user = MyUser.objects.filter(Q(mobile=loginUser) | Q(username=loginUser)).first()
                if check_password(password, user.password):
                    login(request, user)
                    return redirect('home/1.html')
                else:
                    error_tips = '密码错误'
            else:
                error_tips = '用户不存在'
        else:
            # 用户注册
            user = MyUserCreationForm(request.POST)
            if user.is_valid():
                user.save()
                tips = '注册成功'
            else:
                if user.errors.get('username', ''):
                    error_tips = user.errors.get('username', '注册失败')
                else:
                    error_tips = user.errors.get('mobile', '注册失败')
    return render(request, 'user/login.html', locals())


# 用户中心
# 设置用户登录权限
@login_required(login_url='/user/login.html')
def home_view(request, page):
    # 热搜歌曲
    search_song = Dynamic.objects.select_related('song').order_by('-dynamic_search').all()[:4]
    # 分页功能
    song_info = request.session.get('play_list', [])
    page_count = 6
    contacts = myutil.pagination(song_info, page_count, page)
    return render(request, 'user/home.html', locals())


# 退出登录
def logout_view(request):
    logout(request)
    return redirect('/')

user/templates/user/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的音乐-用户中心</title>
    {% load staticfiles %}
    <link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
    <link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "css/user.css" %}">
</head>

<body class="member">
<div class="header">
    <a href="/" class="logo" title="首页"><img src="{% static "image/logo.png" %}"></a>
    <div class="search-box">
        <form id="searchForm" action="{% url 'search:search_view' 1 %}" method="post" target="_blank">
            {% csrf_token %}
            <div class="search-keyword">
                <input id="kword" name="kword" type="text" class="keyword" maxlength="120" placeholder="音乐节"/>
            </div>
            <input id="subSerch" type="submit" class="search-button" value="搜 索"/>
        </form>
        <div id="suggest" class="search-suggest"></div>
        <div class="search-hot-words">
            {% for song in search_song %}
                <a target="play" href="{% url 'play:play_view' song.song.song_id %}">{{ song.song.song_name }}</a>
            {% endfor %}
        </div>
    </div>
</div><!--end header-->

<div class="nav-box">
    <div class="nav-box-inner">
        <ul class="nav clearfix">
            <li><a href="/" target="/">首页</a></li>
            <li><a href="{% url 'ranking:ranking_view' %}" target="ranking">歌曲排行</a></li>
            <li><a href="{% url 'user:home_view' 1 %}" target="home">用户中心</a></li>
        </ul>
    </div>
</div><!--end nav-box-->

<div class="mod_profile js_user_data" style="">
    <div class="section_inner">
        <div class="profile__cover_link">
            <img src="{% static "image/user.jpg" %}" class="profile__cover">
        </div>
        <h1 class="profile__tit">
            <span class="profile__name">{{ user.username }}</span>
        </h1>
        <a href="{% url 'user:logout_view' %}" style="color:white;">退出登录</a>
    </div>
</div>

<div class="main main--profile" style="">
    <div class="mod_tab profile_nav" role="nav" id="nav">
        <span class="mod_tab__item mod_tab__current" id="hear_tab">我听过的歌</span>
    </div>
    <div class="js_box" style="display: block;">
        <div class="profile_cont">
            <div class="js_sub" style="display: block;">
                <div class="mod_songlist">
                    <ul class="songlist__header">
                        <li class="songlist__header_name">歌曲</li>
                        <li class="songlist__header_author">歌手</li>
                        <li class="songlist__header_time">时长</li>
                    </ul>
                    <ul class="songlist__list">
                        {% for item in contacts.object_list %}
                            <li>
                                <div class="songlist__item songlist__item--even">
                                    <div class="songlist__songname">
                                        <a href="{% url 'play:play_view' item.song_id %}"
                                           class="js_song songlist__songname_txt" target="play">{{ item.song_name }}</a>
                                    </div>
                                    <div class="songlist__artist">
                                        <a href="javascript:;" class="singer_name">{{ item.song_singer }}</a>
                                    </div>
                                    <div class="songlist__time">{{ item.song_time }}</div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div><!--end mod_songlist-->

                <!--分页-->
                <div class="page-box">
                    <div class="pagebar" id="pageBar">

                        {% if contacts.has_previous %}
                            <a href="{% url 'user:home_view' contacts.previous_page_number %}" class="prev"
                               target="_self">上一页</a>
                        {% endif %}

                        {% for page in contacts.paginator.page_range %}
                            {% if contacts.number == page %}
                                <span class="sel">{{ page }}</span>
                            {% else %}
                                <a href="{% url 'user:home_view' page %}" target="_self">{{ page }}</a>
                            {% endif %}
                        {% endfor %}

                        {% if contacts.has_next %}
                            <a href="{% url 'user:home_view' contacts.next_page_number %}" class="next" target="_self">下一页</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!-- end main -->
<div class="footer">
    <div class="copyright">
        <p>网站数据信息来源于网络</p>
    </div>
</div>
</body>
</html>

user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的音乐-用户登录/注册</title>
    {% load staticfiles %}
    <link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
    <link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "css/register.css" %}">
</head>

<body class="review">
<div class="wrapper">
    <div class="header clearfix">
        <a href="/" class="logo" target="/">我的音乐</a>
        <span class="logo-tip">Hi,我的音乐欢迎您!</span>
    </div>

    <div class="content clearfix">
        <!-- 登录注册版块 -->
        <div id="unauth_main" class="login-regist">
            <div class="login-box switch_box" style="display:block;">
                <div class="title">用户登录</div>
                <form id="loginForm" class="formBox" action="{% url 'user:login_view' %}" method="post">
                    {% csrf_token %}
                    <div class="itembox user-name">
                        <div class="item">
                            <input type="text" name="loginUser" placeholder="用户名或手机号" class="txt tabInput">
                        </div>
                    </div>
                    <div class="itembox user-pwd">
                        <div class="item">
                            <input type="password" name="password" placeholder="登录密码" class="txt tabInput">
                        </div>
                    </div>
                    {% if tips %}
                        <div><span style="color: green">提示: {{ tips }}</span></div>
                    {% elif error_tips %}
                        <div><span style="color: red">提示: {{ error_tips }}</span></div>
                    {% endif %}
                    <div id="loginBtnBox" class="login-btn">
                        <input id="J_LoginButton" type="submit" value="马上登录" class="tabInput pass-btn"/>
                    </div>
                    <div class="pass-reglink">还没有我的音乐账号？<a class="switch" href="javascript:;">免费注册</a></div>
                </form>
            </div>
            <!-- //登录版块end -->
            <div class="regist-box switch_box" style="display:none;">
                <div class="title">用户注册</div>
                <form id="registerForm" class="formBox" method="post" action="{% url 'user:login_view' %}">
                    {% csrf_token %}
                    <div id="registForm" class="formBox">
                        <div class="itembox user-name">
                            <div class="item">
                                {{ user.username }}
                            </div>
                        </div>
                        <div class="itembox user-name">
                            <div class="item">
                                {{ user.mobile }}
                            </div>
                        </div>
                        <div class="itembox user-pwd">
                            <div class="item">
                                {{ user.password1 }}
                            </div>
                        </div>
                        <div class="itembox user-pwd">
                            <div class="item">
                                {{ user.password2 }}
                            </div>
                        </div>
                        {% if tips %}
                            <div><span style="color: green">提示: {{ tips }}</span></div>
                        {% elif error_tips %}
                            <div><span style="color: red">提示: {{ error_tips }}</span></div>
                        {% endif %}
                        <div class="member-pass clearfix">
                            <input id="agree" name="agree" checked="checked" type="checkbox" value="1"><label
                                for="agree" class="autologon">已阅读并同意用户注册协议</label>
                        </div>
                        <input type="submit" value="免费注册" id="J_RegButton" class="pass-btn tabInput"/>
                        <div class="pass-reglink">已有我的音乐帐号，<a class="switch" href="javascript:;">立即登录</a></div>
                    </div>
                </form>
            </div>
            <!-- //注册版块end -->
        </div>
    </div>
</div>
<script data-main="{% static "js/register.js" %}" src="{% static "js/require.js" %}"></script>
</body>
</html>