comment/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.urls import path
from . import views

app_name = 'comment'
urlpatterns = [
    path('<int:song_id>.html', views.comment_view, name='comment_view'),
]

music/urls.py
from django.contrib import admin
from django.urls import path, include
from index import views
from django.conf.urls import url
from django.views import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('ranking/', include('ranking.urls')),
    path('play/', include('play.urls')),
    path('comment/', include('comment.urls')),
    path('search/', include('search.urls')),
    path('user/', include('user.urls')),
    # 设置项目上线的静态资源路径
    url('^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
]

# 设置404、500错误状态码
handler404 = views.page_not_found
handler500 = views.page_not_found

play/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.urls import path
from . import views

app_name = 'play'
urlpatterns = [
    # 歌曲播放页面
    path('<int:song_id>.html', views.play_view, name='play_view'),
    # 歌曲下载
    path('download/<int:song_id>.html', views.download_view, name='download'),
]

ranking/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.urls import path
from . import views

app_name = 'ranking'
urlpatterns = [
    path('', views.ranking_view, name='ranking_view'),
]

search/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('<int:page>.html', views.search_view, name='search_view'),
]

user/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    # 用户的注册和登录
    path('login.html', views.login_view, name='login_view'),
    # 用户中心
    path('home/<int:page>.html', views.home_view, name='home_view'),
    # 退出用户登录
    path('logout.html', views.logout_view, name='logout_view'),
]

play/models.py
from django.db import models

# Create your models here.

play/views.py
#!/usr/bin/env python
# encoding: utf-8
from django.shortcuts import render
from django.http import FileResponse
from django.utils.http import urlquote
from myutils import myutil
from index.models import *


# Create your views here.
# 歌曲播放首页
def play_view(request, song_id):
    # 热搜歌曲
    search_song = Dynamic.objects.select_related('song').order_by('-dynamic_search').all()[:6]
    # 歌曲信息
    song_info = Song.objects.get(song_id=int(song_id))
    # 播放列表
    play_list = request.session.get('play_list', [])
    song_exist = False
    if play_list:
        for i in play_list:
            if int(song_id) == i['song_id']:
                song_exist = True
    if song_exist == False:
        play_list.append({
            'song_id': int(song_id),
            'song_singer': song_info.song_singer,
            'song_name': song_info.song_name,
            'song_time': song_info.song_time
        })
    request.session['play_list'] = play_list
    # 歌词
    if song_info.song_lyrics != '暂无歌词':
        with open('static/songLyric/' + song_info.song_lyrics, 'r', encoding='utf-8') as f:
            song_lyrics = f.read()
    # 相关歌曲
    song_type = Song.objects.values('song_type').get(song_id=song_id)['song_type']
    song_relevant = Dynamic.objects.select_related('song').filter(song__song_type=song_type).order_by(
        '-dynamic_play').all()[:6]
    # 添加播放次数
    # 扩展功能：可使用session实现每天只添加一次播放次数
    dynamic_info = Dynamic.objects.filter(song_id=int(song_id)).first()
    # 判断歌曲动态信息是否存在，存在就在原来的基础上加1
    if dynamic_info:
        dynamic_info.dynamic_play += 1
        dynamic_info.save()
    else:
        # 若动态信息不存在，则创建新的动态信息
        dynamic_info = Dynamic(dynamic_play=1, dynamic_search=0, dynamic_down=0, song_id=song_id)
        dynamic_info.save()
    return render(request, 'play/play.html', locals())


# 歌曲下载
def download_view(request, song_id):
    # 根据song_id查找歌曲信息, first()用于返回第一个结果
    song_info = Song.objects.filter(song_id=int(song_id)).first()
    # 根据song_id获取歌曲动态信息表，添加下载次数
    dynamic_info = Dynamic.objects.filter(song_id=int(song_id)).first()
    # 判断歌曲动态信息是否存在，存在就在原来的基础上加1
    if dynamic_info:
        dynamic_info.dynamic_down += 1
        dynamic_info.save()
    else:
        # 若动态信息不存在，则创建新的动态信息
        dynamic_info = Dynamic(dynamic_play=0, dynamic_search=0, dynamic_down=1, song_id=int(song_id))
        dynamic_info.save()
    # 将读取的歌曲文件内容写入StreamingHttpResponse对象，并以字节流的方式返回给用户
    file = 'static/songFile/' + song_info.song_file
    filename = song_info.song_name + '.mp3'
    response = FileResponse(myutil.file_iterator(file))
    response['Content-Type'] = 'application/octet-stream'
    # 下载中文文件名文件：使用urlquote()函数处理文件名，始之支持中文显示
    # response['Content-Disposition'] = 'attachment; filename={0}'.format(filename.encode('utf-8').decode('ISO-8859-1'))
    response['Content-Disposition'] = 'attachment; filename={0}'.format(urlquote(filename))
    return response

play/templates/play/play.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的音乐-音乐播放</title>
    {% load staticfiles %}
    <link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
    <link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "css/play.css" %}">
    <style>
        @-webkit-keyframes rotation {
            from {
                -webkit-transform: rotate(0deg);
            }
            to {
                -webkit-transform: rotate(360deg);
            }
        }
        .Rotation {
            -webkit-transform: rotate(360deg);
            animation: rotation 30s linear infinite;
            -moz-animation: rotation 30s linear infinite;
            -webkit-animation: rotation 30s linear infinite;
            -o-animation: rotation 30s linear infinite;
        }
    </style>
</head>

<body>
<div class="header">
    <a href="/" class="logo" title="首页"><img src="{% static "image/logo.png" %}"></a>
    <div class="search-box">
        <!-- 歌曲查询 -->
        <form id="searchForm" action="{% url 'search:search_view' 1 %}" method="post" target="_blank">
            {% csrf_token %}
            <div class="search-keyword">
                <input id="kword" name="kword" type="text" class="keyword" maxlength="120" placeholder="音乐节"/>
            </div>
            <input id="subSerch" type="submit" class="search-button" value="搜 索"/>
        </form>
        <div id="suggest" class="search-suggest"></div>
        <div class="search-hot-words">
            {% for song in search_song %}
                <a target="play" href="{% url 'play:play_view' song.song.song_id %}">{{ song.song.song_name }}</a>
            {% endfor %}
        </div>
    </div>
</div><!--end header-->
<div class="nav-box">
    <div class="nav-box-inner">
        <ul class="nav clearfix">
            <li><a href="/" , target="/">首页</a></li>
            <li><a href="{% url 'ranking:ranking_view' %}" target="ranking">歌曲排行</a></li>
            <li><a href="{% url 'user:home_view' 1 %}" target="home">用户中心</a></li>
        </ul>
    </div>
</div><!--end nav-box-->
<!--后期修改-->
<div class="wrapper clearfix">
    <div class="content">
        <div class="product-detail-box clearfix">
            <div class="product-pics">
                <div class="music_box">
                    <div id="jquery_jplayer_1" class="jp-jplayer" data-url=
                            {% static "songFile/" %}{{ song_info.song_file }}></div>
                    <div class="jp_img layz_load pic_po" title="点击播放"><img class="Rotation img" data-src=
                            {% static "songImg/" %}{{ song_info.song_img }}></div>
                    <div id="jp_container_1" class="jp-audio">
                        <div class="jp-gui jp-interface">
                            <div class="jp-time-holder clearfix">
                                <div class="jp-progress">
                                    <div class="jp-seek-bar">
                                        <div class="jp-play-bar"></div>
                                    </div>
                                </div>
                                <div class="jp-time">
                                    <span class="jp-current-time"></span> /
                                    <span class="jp-duration"></span>
                                </div>
                            </div>
                            <div class="song_error_corr" id="songCorr">
                                <b class="err_btn">纠错</b>
                                <ul>
                                    <li><span>歌词文本错误</span></li>
                                    <li><span>歌词时间错误</span></li>
                                    <li><span>歌曲错误</span></li>
                                </ul>
                            </div>
                            <div class="jp-volume-bar">
                                <div class="jp-volume-bar-value"></div>
                            </div>
                            <ul class="jp-controls clearfix">
                                <li><a class="jp-play" tabindex="1" title="play"></a><a class="jp-pause" tabindex="1"
                                                                                        title="pause"></a></li>
                                <li><a class="jp-stop" tabindex="1" title="stop"></a></li>
                                <li><a class="jp-repeat" tabindex="1" title="repeat"></a><a class="jp-repeat-off"
                                                                                            tabindex="1"
                                                                                            title="repeat off"></a></li>
                                <li class="sound"><a class="jp-mute" tabindex="1" title="mute"></a><a class="jp-unmute"
                                                                                                      tabindex="1"
                                                                                                      title="unmute"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="jplayer_content">
                        <ul id="lrc_list" class="lrc_list"></ul>
                    </div>
                </div><!--end music_box-->
                <textarea id="lrc_content" style="display: none;">
                      {{ song_lyrics }}
                    </textarea>
            </div><!--end product-pics-->
            <div class="product-detail-main">
                <div class="product-price">
                    <h1 id="currentSong">{{ song_info.song_name }}</h1>
                    <div class="product-price-info">
                        <span>歌手：{{ song_info.song_singer }}</span>
                    </div>
                    <div class="product-price-info">
                        <span>专辑：{{ song_info.song_album }}</span>
                        <span>语种：{{ song_info.song_languages }}</span>
                    </div>
                    <div class="product-price-info">
                        <span>流派：{{ song_info.song_type }}</span>
                        <span>发行时间：{{ song_info.song_release }}</span>
                    </div>
                </div><!--end product-price-->
                <div class="product-comment">
                    <div class="links clearfix">
                        <a class="minimum-link-A click_down"
                           href="{% url 'play:download' song_info.song_id %}">下载</a>
                        <a class="minimum-link-A" href="{% url 'comment:comment_view' song_info.song_id %}"
                           target="comment">歌曲点评</a>
                    </div><!-- end links-->
                    <h3 class="list_title">当前播放列表</h3>
                    <ul class="playing-li" id="songlist">
                        <!--播放列表-->
                        {% for list in play_list %}
                            {% if list.song_id == song_info.song_id %}
                                <li data-id="{{ list.song_id }}" class="current">
                                    {% else %}
                                <li data-id="{{ list.song_id }}">
                            {% endif %}
                        <span class="num">{{ forloop.counter }}</span>
                        <a class="name" href="{% url 'play:play_view' list.song_id %}"
                           target="play">{{ list.song_name }}</a>
                        <a class="singer" href="javascript:;" target="_blank">{{ list.song_singer }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="nplayL-btns" id="playleixin">
                        <ul>
                            <li class="order current" data-run="order">
                                <a class="icon" href="javascript:void(0)" title="顺序播放"></a>
                            </li>
                            <li class="single" data-run="single">
                                <a class="icon" title="单曲循环" href="javascript:void(0)"></a>
                            </li>
                            <li class="random" data-run="random">
                                <a class="icon" title="随机播放" href="javascript:void(0)"></a>
                            </li>
                            <li class="next" data-run="next">
                                <a href="javascript:void(0)"><i></i>播放下一首</a>
                            </li>
                        </ul>
                    </div><!--end nplayL-btns-->
                </div><!-- end product-comment -->
            </div><!-- end product-detail-main -->
        </div><!-- end product-detail-box -->

        <div class="section">
            <div class="section-header">
                <h3>相关歌曲</h3>
            </div>
            <div class="section-content">
                <div class="parts-box">
                    <a href="javascript:;" target="_self" id="J_PartsPrev" class="prev-btn"><i></i></a>
                    <div class="parts-slider" id="J_PartsList">
                        <div class="parts-list-wrap f_w">
                            <ul id="" class="parts-list clearfix f_s">
                                {% for item in song_relevant %}
                                    <li>
                                        {% if item.song.song_id != song_info.song_id %}
                                            <a class="pic layz_load pic_po"
                                               href="{% url 'play:play_view' item.song.song_id %}"
                                               target="play">
                                                <img data-src="{% static "songImg/" %}{{ item.song.song_img }}">
                                            </a>
                                            <h4><a href="{% url 'play:play_view' item.song.song_id %}"
                                                   target="play">{{ item.song.song_name }}</a></h4>
                                            <a href="javascript:;"
                                               class="J_MoreParts accessories-more">{{ item.song.song_singer }}</a>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <a href="javascript:;" target="_self" id="J_PartsNext" class="next-btn"><i></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer">
    <div class="copyright">
        <p>网站数据信息来源于网络</p>
    </div>
</div>
<script data-main="{% static "js/play.js" %}" src="{% static "js/require.js" %}"></script>
</body>
</html>